name: tabiblib
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  awesome_bottom_bar: ^1.2.2
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.5
  dio: ^5.1.1
  file_picker: ^5.2.7
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_localizations:
    sdk: flutter
  fpdart: ^0.5.0
  hooks_riverpod: ^2.3.2
  intl: ^0.17.0
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  jiffy: ^5.0.0
  mask_text_input_formatter: ^2.4.0
  percent_indicator: ^4.2.3
  shared_preferences: ^2.1.0
  sliding_sheet: ^0.5.2
  tuple: ^2.0.1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.12.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  isar_generator: ^3.0.5

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo_icon.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
